version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "main"
    commit-message:
      prefix: ':green_heart: chore(ci)'

  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    target-branch: "main"
    commit-message:
      prefix: ':arrow_up: chore(deps)'
