name: New Bug 
description: Report a new bug
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      ## New Bug Report
- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    placeholder: |
      Describe the exact steps which reproduce the problem in as many details as possible. 
      For example, start by explaining how you started THipster, e.g. which command exactly you used in the terminal, or how you started THipster otherwise. 
      When listing steps, don't just say what you did, but explain how you did it.
      Include links to files or GitHub projects, or copy/pasteable snippets, which you use in those examples. 
      If you're providing snippets in the issue, use Markdown code blocks : https://help.github.com/articles/markdown-basics/#multiple-lines.
  validations:
    required: true
- type: textarea
  id: observed-behavior
  attributes:
    label: Observed behavior after following the steps
    placeholder: |
      Point out what exactly is the problem with that behavior.
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    placeholder: |
      Explain which behavior you expected to see instead and why.
  validations:
    required: true
- type: textarea
  id: thipster-version
  attributes:
    label: THipster version
    placeholder: |
      run thipster -v and paste the result here!
  validations:
    required: true
- type: textarea
  id: problem-start-date
  attributes:
    label: Start date and occurence
    placeholder: |
      Did the problem start happening recently (e.g. after updating to a new version of THipster) or was this always a problem?
      If the problem started happening recently, can you reproduce the problem in an older version of THipster? 
      What's the most recent version in which the problem doesn't happen?
      Can you reliably reproduce the issue? 
      If not, provide details about how often the problem happens and under which conditions it normally happens.
  validations:
    required: true
- type: dropdown
  id: host-os
  attributes:
    label: OS name
    multiple: false
    options:
    - Linux
    - MacOS
    - Windows
    - Other
  validations:
    required: true
- type: textarea
  id: host-os-details
  attributes:
    label: OS details
    placeholder: |
      Version and details of the OS you're using. Are you running THipster in a virtual machine? 
      If so, which VM software are you using and which operating systems and versions are used for the host and the guest?
  validations:
    required: true
- type: textarea
  id: python-version
  attributes:
    label: Python version
    placeholder: |
      What Python version are you using?
      You can find the Python version with: python --version
  validations:
    required: true
- type: dropdown
  id: Component
  attributes:
    label: Component
    description: "Which component(s) in the toolchain is this related to?"
    multiple: true
    options:
    - Engine
    - CLI
    - Parser
    - Auth
    - Resource Library
    - Documentation
    - Other
  validations:
    required: true
- type: textarea
  id: additional-info
  attributes:
    label: Additional infos
    placeholder: |
      Add any additional context information or screenshots you think are useful.
  validations:
    required: false
