name: New Bug 
description: Report a new bug
labels: ["bug"]
body:
- type: markdown
  attributes:
    value: |
      ## New Bug Report
- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    placeholder: |
      Describe the exact steps which reproduce the problem in as many details as possible. 
      For example, start by explaining how you started THipster, e.g. which command exactly you used in the terminal, or how you started THipster otherwise. 
      When listing steps, don't just say what you did, but explain how you did it.
      Include links to files or GitHub projects, or copy/pasteable snippets, which you use in those examples. 
      If you're providing snippets in the issue, use Markdown code blocks : https://help.github.com/articles/markdown-basics/#multiple-lines.
  validations:
    required: true
- type: textarea
  id: observed-behavior
  attributes:
    label: Observed behavior after following the steps
    placeholder: |
      Point out what exactly is the problem with that behavior.
  validations:
    required: true
- type: textarea
  id: expected-behavior
  attributes:
    label: Expected behavior
    placeholder: |
      Explain which behavior you expected to see instead and why.
- type: dropdown
  id: Component
  attributes:
    label: Component
    description: "Which component(s) in the toolchain is this related to?"
    multiple: true
    options:
    - Engine
    - CLI
    - Parser
    - Auth
    - Resource Library
    - Documentation
  validations:
    required: false
